### ISSUE TITLE
[US #04 e #05] Pesquisa: manipulação das bandas disponíveis (para tiles, realce e download)

### ISSUE THREAD

**Issue by ThHenrique** [Equipe-Polaris-DSM-2021/api#6]
- **RF 02**: Serviço de geração de tiles dinâmicos
- **RF 03**: Exibição das imagens em cores naturais e realçadas

#### Qual o objetivo desta tarefa?
Descobrir o que dá pra fazer com as bandas disponibilizadas pela API externa:
- Dá pra juntar? 
- Dá pra separar? 
- Dá pra fazer um zip de todas as bandas de uma mesma imagem? 
- Dá pra aplicar filtros de cor/realce nelas juntas ou separadas?

**Comment by MariaGabrielaReis** [comment]
Parabéns, @GabrielCamargoL , o travalho está ótimo, continue assim :sparkling_heart:
